server:
  webHostport: localhost:1234
  grpcHostport: localhost:2345
  credentials: /home/mori/vox/credentials.json

storage:
#  sqlite:
#    fpath: "foo.db"
  lionrock:
    hostport: localhost:6565
    prefix: "voxmachina"
    name: "fdb"
